name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-upload:
    name: Build ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive: tar.gz
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            archive: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MUSL tools (Linux musl only)
        if: runner.os == 'Linux' && contains(matrix.target, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build (release)
        shell: bash
        run: |
          set -euxo pipefail
          cargo build --release -p cli --bin owlsol --target ${{ matrix.target }}

      - name: Package artifacts
        shell: bash
        run: |
          set -euxo pipefail
          TAG=${GITHUB_REF_NAME}
          BIN_NAME="owlsol"
          EXT=""
          if [[ "${{ matrix.os }}" == "Windows" ]]; then EXT=".exe"; fi
          OUTDIR="dist/${BIN_NAME}-${TAG}-${{ matrix.target }}"
          mkdir -p "$OUTDIR"
          cp target/${{ matrix.target }}/release/${BIN_NAME}${EXT} "$OUTDIR/"
          # include docs
          [[ -f README.md ]] && cp README.md "$OUTDIR/" || true
          [[ -f LICENSE ]] && cp LICENSE "$OUTDIR/" || true
          # archive
          mkdir -p dist
          ARCHIVE_PATH=""
          if [[ "${{ matrix.archive }}" == "zip" ]]; then
            (cd dist && zip -r "${BIN_NAME}-${TAG}-${{ matrix.target }}.zip" "${BIN_NAME}-${TAG}-${{ matrix.target }}")
            ARCHIVE_PATH="dist/${BIN_NAME}-${TAG}-${{ matrix.target }}.zip"
          else
            (cd dist && tar -czf "${BIN_NAME}-${TAG}-${{ matrix.target }}.tar.gz" "${BIN_NAME}-${TAG}-${{ matrix.target }}")
            ARCHIVE_PATH="dist/${BIN_NAME}-${TAG}-${{ matrix.target }}.tar.gz"
          fi
          # checksum per archive
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum "$ARCHIVE_PATH" > "${ARCHIVE_PATH}.sha256"
          else
            shasum -a 256 "$ARCHIVE_PATH" > "${ARCHIVE_PATH}.sha256"
          fi

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/owlsol-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }}
            dist/owlsol-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
